# Color scheme
[colors.primary]
background = "#393D44"
foreground = "#E3ECEA"

[colors.normal]
black   = "#393D44"
red     = "#D6AA96"
green   = "#9FD8A6"
yellow  = "#D0E1A9"
blue    = "#94B0DC"
magenta = "#A7D3E6"
cyan    = "#A3E5FE"
white   = "#E3ECEA"

[colors.bright]
black   = "#9EA5A3"
red     = "#D6AA96"
green   = "#9FD8A6"
yellow  = "#D0E1A9"
blue    = "#94B0DC"
magenta = "#A7D3E6"
cyan    = "#A3E5FE"
white   = "#E3ECEA"

# Font settings
[font]
normal.family = "DepartureMono"
normal.style = "Regular"
bold.family = "DepartureMono"
bold.style = "Bold"
italic.family = "DepartureMono"
italic.style = "Italic"
size = 12.0

# Cursor settings
[cursor]
style.shape = "Beam"
style.blinking = "On"
blink_interval = 512 
vi_mode_style = "Beam"

# Window settings
[window]
dynamic_padding = false
padding={ x = 10, y = 6 }

